---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: archivebox
spec:
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: {{ .Values.storage.nfs.path }}
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
