---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: archivebox-pv
spec:
  capacity:
    storage: {{ .Values.storage.capacity }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: {{ .Values.storage.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.nodeAffinityHostname }}
