---
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: archivebox
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.request }}
  storageClassName: nfs