---
apiVersion: v1
kind: Service
metadata:
  name: archivebox
spec:
  ports:
  - port: {{ .Values.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.archivebox.port }}
  selector:
    app: archivebox
  type: ClusterIP

